apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v2
      weight: 70
    - destination:
        host: reviews
        subset: v3
      weight: 30
  - route:
    - destination:
        host: reviews
        subset: v1